env:
  node: true
  browser: true

parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'

ignorePatterns:
  - '/dist'

settings:
  react:
    version: '16.13.1'

rules:
  function-paren-newline: 0
  no-confusing-arrow: 0
  implicit-arrow-linebreak: 0
  object-curly-newline: 0
  operator-linebreak: 0
  import/prefer-default-export: 0
  no-console: 1
  arrow-parens:
    - error
    - as-needed
  comma-dangle:
    - error
    - objects: only-multiline
      arrays: only-multiline
      functions: ignore
  react/prop-types: 0
